"""Initial build of database

Revision ID: 8c4eddde7535
Revises: 
Create Date: 2020-10-14 13:37:31.693315

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8c4eddde7535'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('API_KEY', sa.String(length=100), nullable=False),
    sa.Column('API_SECRET', postgresql.BYTEA(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    op.create_table('campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('created', 'active', 'completed', 'finished', name='campaign_status'), nullable=False),
    sa.Column('label_translations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_started', sa.DateTime(), nullable=True),
    sa.Column('date_completed', sa.DateTime(), nullable=True),
    sa.Column('date_finished', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('imageset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('created', 'finished', name='imageset_status'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('blobstorage_path', sa.String(length=1024), nullable=True),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_finished', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blobstorage_path'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blobstorage_path', sa.String(length=1024), nullable=False),
    sa.Column('imageset_id', sa.Integer(), nullable=True),
    sa.Column('date_taken', sa.DateTime(), nullable=True),
    sa.Column('location_taken', sa.String(length=1024), nullable=True),
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tss_id', sa.String(length=128), nullable=True),
    sa.Column('filetype', sa.String(length=128), nullable=True),
    sa.Column('filesize', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('date_added', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['imageset_id'], ['imageset.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blobstorage_path'),
    sa.UniqueConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('image-admin', 'labeler', name='role_types'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subject'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('campaign_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('labeled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_image_id', sa.Integer(), nullable=False),
    sa.Column('label_translated', sa.String(length=128), nullable=False),
    sa.Column('label_original', sa.String(length=128), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('date_added', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('x_min', sa.Integer(), nullable=False),
    sa.Column('x_max', sa.Integer(), nullable=False),
    sa.Column('y_min', sa.Integer(), nullable=False),
    sa.Column('y_max', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_image_id'], ['campaign_image.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('object')
    op.drop_table('campaign_image')
    op.drop_table('roles')
    op.drop_table('image')
    op.drop_table('imageset')
    op.drop_table('campaign')
    op.drop_table('user')
    # ### end Alembic commands ###
