"""Added enabled property to user

Revision ID: f9d0c25a835e
Revises: 7545bb352d84
Create Date: 2020-10-15 10:58:09.922748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9d0c25a835e'
down_revision = '7545bb352d84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('enabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'enabled')
    # ### end Alembic commands ###
